package com.cju.likelion.cardcollection.collection.service;
import com.cju.likelion.cardcollection.auth.domain.User; import com.cju.likelion.cardcollection.auth.exception.InvalidCredentialsException; import com.cju.likelion.cardcollection.auth.repository.UserRepository;
import com.cju.likelion.cardcollection.card.domain.Card; import com.cju.likelion.cardcollection.card.dto.CardResponse; import com.cju.likelion.cardcollection.card.repository.CardRepository;
import com.cju.likelion.cardcollection.collection.domain.*; import com.cju.likelion.cardcollection.collection.dto.*; import com.cju.likelion.cardcollection.collection.exception.CollectionDomainException; import com.cju.likelion.cardcollection.collection.repository.*;
import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;

@Service public class UserCollectionService {
    private final UserRepository users; private final CardRepository cards; private final UserCollectionRepository collections; private final CollectionCardRepository collectionCards;
    public UserCollectionService(UserRepository users, CardRepository cards, UserCollectionRepository collections, CollectionCardRepository collectionCards) { this.users=users; this.cards=cards; this.collections=collections; this.collectionCards=collectionCards; }
    @Transactional public UserCollectionResponse create(UUID userId, CollectionCreateRequest r) { UserCollection c=collections.save(UserCollection.custom(activeUser(userId), r.name().trim(), r.description(), r.coverImageUrl())); return UserCollectionResponse.summary(c,0); }
    @Transactional(readOnly=true) public List<UserCollectionResponse> list(UUID userId) { activeUser(userId); return collections.findByUserIdOrderByUpdatedAtDesc(userId).stream().map(c->UserCollectionResponse.summary(c,collectionCards.countByIdCollectionId(c.getId()))).toList(); }
    @Transactional(readOnly=true) public UserCollectionResponse get(UUID userId, UUID id) { UserCollection c=find(userId,id); return UserCollectionResponse.detail(c,collectionCards.findByIdCollectionIdOrderByAddedAtDesc(id).stream().map(link->CardResponse.from(link.getCard())).toList()); }
    @Transactional public UserCollectionResponse update(UUID userId, UUID id, CollectionUpdateRequest r) { UserCollection c=find(userId,id); c.update(r.name().trim(),r.description(),r.coverImageUrl()); return UserCollectionResponse.summary(c,collectionCards.countByIdCollectionId(id)); }
    @Transactional public void delete(UUID userId, UUID id) { collections.delete(find(userId,id)); }
    @Transactional public UserCollectionResponse addCard(UUID userId, UUID id, CollectionCardAddRequest r) { UserCollection c=find(userId,id); Card card=cards.findByIdAndUserId(r.cardId(),userId).orElseThrow(()->error("COLLECTION_CARD_NOT_OWNED","본인 소유 카드만 컬렉션에 추가할 수 있습니다.",HttpStatus.NOT_FOUND)); CollectionCardId linkId=new CollectionCardId(id,r.cardId()); if(collectionCards.existsById(linkId)) throw error("COLLECTION_CARD_ALREADY_ADDED","이미 컬렉션에 추가된 카드입니다.",HttpStatus.CONFLICT); collectionCards.save(CollectionCard.of(c,card)); return get(userId,id); }
    @Transactional public void removeCard(UUID userId, UUID id, UUID cardId) { find(userId,id); CollectionCardId linkId=new CollectionCardId(id,cardId); if(!collectionCards.existsById(linkId)) throw error("COLLECTION_CARD_NOT_FOUND","컬렉션에 포함되지 않은 카드입니다.",HttpStatus.NOT_FOUND); collectionCards.deleteById(linkId); }
    private User activeUser(UUID id){return users.findByIdAndDeletedAtIsNull(id).orElseThrow(InvalidCredentialsException::new);} private UserCollection find(UUID userId,UUID id){activeUser(userId);return collections.findByIdAndUserId(id,userId).orElseThrow(()->error("COLLECTION_NOT_FOUND","컬렉션을 찾을 수 없습니다.",HttpStatus.NOT_FOUND));} private CollectionDomainException error(String c,String m,HttpStatus s){return new CollectionDomainException(c,m,s);}
}
